import {
  BUTTON_TYPE_ADD,
  BUTTON_TYPE_SUB,
  COUNTER_BUTTON_SIZE,
  EVENT_NAME_MEDITATION_ENDED,
  EVENT_NAME_MEDITATION_STARTED,
  FIVE_MINUTES_IN_SECONDS,
  MEDITATION_ENDED,
  MEDITATION_NOT_STARTED,
  MEDITATION_ONGOING
} from '@pages/meditation/constants/meditation';

export default {
  COUNTER_BUTTON_SIZE,
  MEDITATION_NOT_STARTED,
  MEDITATION_ONGOING,
  MEDITATION_ENDED,
  EVENT_NAME_MEDITATION_STARTED,
  EVENT_NAME_MEDITATION_ENDED,
  FIVE_MINUTES_IN_SECONDS,
  BUTTON_TYPE_ADD,
  BUTTON_TYPE_SUB
};
