const MEDITATION_TIME_UNIT = 60;
const COUNTER_BUTTON_SIZE = 80;
const BUTTON_TYPE_ADD = 'add';
const BUTTON_TYPE_SUB = 'sub';

const ICON_NAME_PLAY = 'play_arrow';
const ICON_NAME_PAUSE = 'pause';

const MEDITATION_NOT_STARTED = '명상 시간을 설정해주세요.';
const MEDITATION_ONGOING = '편안한 명상 되세요.';
const MEDITATION_ENDED = '명상이 종료되었습니다.';

const CONCENTRATION_KEY = 'CONCENTRATION';
const ANXIETY_KEY = 'ANXIETY';
const FREEDOM_KEY = 'FREEDOM';
const RELAXATION_KEY = 'RELAXATION';
const STRESS_KEY = 'STRESS';

export {
  COUNTER_BUTTON_SIZE,
  MEDITATION_NOT_STARTED,
  MEDITATION_ONGOING,
  MEDITATION_ENDED,
  MEDITATION_TIME_UNIT,
  BUTTON_TYPE_ADD,
  BUTTON_TYPE_SUB,
  ICON_NAME_PLAY,
  ICON_NAME_PAUSE,
  CONCENTRATION_KEY,
  ANXIETY_KEY,
  FREEDOM_KEY,
  RELAXATION_KEY,
  STRESS_KEY
};
